- name: Install windows features-OpcenterEX_v8_Prereqs
  hosts: windows2 # Replace with your target Windows host group
  gather_facts: true

  tasks:
    - name: Install desired Windows features
      ansible.windows.win_feature:
        name: 
           - Web-Server
           - Web-WebServer
           - Web-Common-Http
           - Web-Default-Doc
           - Web-Dir-Browsing
           - Web-Http-Errors
           - Web-Static-Content
           - Web-Http-Redirect
           - Web-Health
           - Web-Http-Logging
           - Web-Custom-Logging
           - Web-Log-Libraries
           - Web-ODBC-Logging
           - Web-Request-Monitor
           - Web-HTTP-Tracing
           - Web-Performance
           - Web-Stat-Compression
           - Web-Dyn-Compression
           - Web-Security
           - Web-Filtering
           - Web-Digest-Auth
           - Web-Url-Auth
           - Web-Windows-Auth
           - Web-App-Dev
           - Web-AppInit
           - Web-Net-Ext45
           - Web-Asp-Net45
           - Web-ISAPI-Ext
           - Web-ISAPI-Filter
           - Web-Includes
           - Web-Mgmt-Tools
           - Web-Mgmt-Console
           - Web-Mgmt-Compat
           - Web-Metabase
           - Web-Lgcy-Mgmt-Console
           - Web-Scripting-Tools
           - NET-Framework-45-ASPNET
           - NET-WCF-HTTP-Activation45
           - WAS
           - WAS-Process-Model
           - WAS-Config-APIs

        state: present
        include_sub_features: true # Install sub-features if required
        restart: true
 
