- name: Install windows features
  hosts: windows2 # Replace with your target Windows host group
  gather_facts: false

  tasks:
    - name: Install desired Windows features
      ansible.windows.win_feature:
        name: 
      
           - FileAndStorage-Services
           - Storage-Services
           - Web-WebServer
           - Web-Common-Http
           - Web-Default-Doc
           - Web-Dir-Browsing
           - Web-Http-Errors
           - Web-Static-Content
           - Web-DAV-Publishing
           - Web-Health
           - Web-Http-Logging
           - Web-Performance
           - Web-Security
           - Web-Filtering
           - Web-App-Dev
           - Web-Net-Ext45
           - Web-Asp-Net45
           - Web-ISAPI-Ext
           - Web-ISAPI-Filter
           - Web-Mgmt-Tools
           - Web-Mgmt-Console
           - NET-Framework-45-Core
           - NET-Framework-45-ASPNET
           - NET-WCF-Services45
           - NET-WCF-HTTP-Activation45
           - NET-WCF-MSMQ-Activation45
           - NET-WCF-Pipe-Activation45
           - NET-WCF-TCP-Activation45
           - NET-WCF-TCP-PortSharing45
           - MSMQ
           - MSMQ-Services
           - MSMQ-Server
           - FS-SMB1
           - PowerShell
           - PowerShell-ISE
           - WAS
           - WAS-Process-Model
           - WAS-Config-APIs
           - WoW64-Support

        state: present
        include_sub_features: true # Install sub-features if required
        restart: true
 
